### PR TITLE
feat: Run classes in parallel if they are in a single collection

### PR DESCRIPTION
**Pull request by pregress**
Fix for #9 ; also updated readme with an example.

The default xunit behavior stays the same, unless you add the `EnableParallelizationAttribute` on the collection definition

### CODE REVIEW

**Comment by pregress** [comment]
@meziantou could you have a look & possibly merge and release this?

**Comment by pregress** [comment]
@meziantou Is it possible to have a look?

**Comment by meziantou** [comment]
Sorry for the delay. I missed the first notification :(

**Comment by meziantou** [comment]
There is a small build error (check the warnings locally)

**Pull request merged**
